---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- My First Group:
    - Watchtower:
        widgets:
            - type: watchtower
              url: http://watchtower:8080
              key: hjdshjdszuzudfdfskjdfsnnfdsdsfzudszufdsfnfdsk
    - Traefik:
        widgets:
            - type: traefik
              url: http://reverse-proxy:8080

- My Second Group:
    - My Second Service:
        href: http://localhost/
        description: Homepage is the best

- My Third Group:
    - My Third Service:
        href: http://localhost/
        description: Homepage is 😎
